### ISSUE TITLE
Kubernetes 1.21 is no longer supported on AWS

### ISSUE THREAD

**Issue by aremedis** [udacity/cd1898-Observing-Cloud-Resources#6]
/cd1898-Observing-Cloud-Resources/blob/master/starter/terraform/modules/eks/eks.tf

`
resource "aws_eks_cluster" "cluster" {
   name     = "${var.name}-cluster"
   version  = "1.21"
   role_arn = aws_iam_role.eks_cluster_role.arn
`

needs to be updated to a supported version.

**Comment by viirtueisaac** [comment]
This is still an issue and needs to be manually updated in order to proceed with the project. This is not documented anywhere and is a frustrating find.

**Comment by Sezotove** [comment]
~1.5 years to get a config updated for your over priced and subpar "course".  This is a shining example of why people request refunds and leave poor reviews on your services.

**Comment by islamalsawy** [comment]
@Sezotove Thank you for your feedback. We sincerely apologize for the delay in updating the configuration. We understand that AWS EKS continuously releases new versions every 3-4 months, and we will keep an eye on the latest supported version to ensure our configurations remain current. We're committed to improving our processes and delivering a better experience moving forward. If there's anything specific we can assist with now, please let us know. Thank you for your understanding.
